kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: default
    image: node:10
    commands:
      - npm ci

  - name: build
    pull: default
    image: node:10
    commands:
      - npm run build
