kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: default
    image: node:10
    commands:
      - npm ci


  - name: build
    pull: default
    image: node:10
    commands:
      - npm run build

  - name: deploy
    pull: default
    image: devillex/docker-firebase
    project_id: staging
    message: Autodeploy of commit $$COMMIT
    targets: hosting
    debug: true
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    commands:
      - firebase deploy --token $FIREBASE_TOKEN

  - name: lighthouse-check
    pull: default
    user: root
    image: kporras07/lighthouse-ci
    environment:
      GITHUB_OWNER:
        from_secret: GITHUB_OWNER
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - |
        npm run lh -- https://drone-test-982a9.web.app/ --chrome-flags="--headless --no-sandbox" --perf=100 --pwa=100
         --seo=100 --a11y=100 --bp=100
