kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: default
    image: node:10
    commands:
      - npm ci
      - npm i -g firebase-tools

  - name: build
    pull: default
    image: node:10
    commands:
      - npm run build

    firebase:
      image: google/drone-firebase
      token: >
        $$FIREBASE_TOKEN
      project_id: drone-test-982a9
      message: Autodeploy of commit $$COMMIT
      targets: hosting
