kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: default
    image: node:10
    commands:
      - npm ci


  - name: build
    pull: default
    image: node:10
    commands:
      - npm run build

  - name: deploy
    pull: default
    image: devillex/docker-firebase
    token: >
      $$FIREBASE_TOKEN
    project_id: staging
    message: Autodeploy of commit $$COMMIT
    targets: hosting
    debug: true
    commands:
      - firebase deploy --token $FIREBASE_TOKEN
