kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: default
    image: node:10
    commands:
      - npm ci


  - name: build
    pull: default
    image: node:10
    commands:
      - npm run build

  - name: deploy
    pull: default
    image: devillex/docker-firebase
    token: >
      $$FIREBASE_TOKEN
    project_id: staging
    message: Autodeploy of commit $$COMMIT
    targets: hosting
    debug: true
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    commands:
      - firebase deploy --token $FIREBASE_TOKEN

  - name: lighthouse-check
    pull: default
    image: zenika/alpine-chrome
    commands:
      - npm install -g lighthouse
      - lighthouse https://drone-test-982a9.web.app/
